### config ###

# See https://www.mkdocs.org/user-guide/configuration/.

INHERIT: !ENV MKDOCS_BASE_CONFIG

### navigation ###

nav:
  - index.md
  - Livro:
      - Introdução: 00-intro.md
      - Uso básico: 01-basic-usage.md
      - Bibliotecas: 02-libraries.md
      - CLI / Comandos: 03-cli.md
      - Esquema do composer.json: 04-schema.md
      - Repositórios: 05-repositories.md
      - Configuração: 06-config.md
      - Utilitários do runtime do Composer: 07-runtime.md
      - Comunidade: 08-community.md
  - Artigos:
      - Apelidos: articles/aliases.md
      - Autenticação para pacotes e repositórios privados: articles/authentication-for-private-packages.md
      - articles/autoloader-optimization.md
      - articles/composer-platform-dependencies.md
      - articles/custom-installers.md
      - articles/handling-private-packages.md
      - articles/plugins.md
      - articles/repository-priorities.md
      - articles/resolving-merge-conflicts.md
      - articles/scripts.md
      - articles/troubleshooting.md
      - articles/vendor-binaries.md
      - articles/versions.md
  - FAQs:
      - faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md
      - faqs/how-to-install-composer-programmatically.md
      - faqs/how-to-install-untrusted-packages-safely.md
      - faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md
      - faqs/which-version-numbering-system-does-composer-itself-use.md
      - faqs/why-are-unbound-version-constraints-a-bad-idea.md
      - faqs/why-are-version-constraints-combining-comparisons-and-wildcards-a-bad-idea.md
      - faqs/why-cant-composer-load-repositories-recursively.md
