### config ###

# See https://www.mkdocs.org/user-guide/configuration/.

INHERIT: !ENV MKDOCS_BASE_CONFIG

### navigation ###

nav:
  - doc/index.md
  - Livro:
      - Introdução: doc/00-intro.md
      - "Uso básico": doc/01-basic-usage.md
      - doc/02-libraries.md
      - "CLI / Comandos": doc/03-cli.md
      - "Esquema do composer.json": doc/04-schema.md
      - doc/05-repositories.md
      - "Configuração": doc/06-config.md
      - "Utilitários do runtime do Composer": doc/07-runtime.md
      - doc/08-community.md
  - Artigos:
      - "Apelidos": doc/articles/aliases.md
      - "Autenticação para pacotes e repositórios privados": doc/articles/authentication-for-private-packages.md
      - "Otimização do carregador automático": doc/articles/autoloader-optimization.md
      - doc/articles/composer-platform-dependencies.md
      - doc/articles/custom-installers.md
      - doc/articles/handling-private-packages.md
      - doc/articles/plugins.md
      - doc/articles/repository-priorities.md
      - doc/articles/resolving-merge-conflicts.md
      - doc/articles/scripts.md
      - doc/articles/troubleshooting.md
      - doc/articles/vendor-binaries.md
      - doc/articles/versions.md
  - FAQs:
      - doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md
      - doc/faqs/how-to-install-composer-programmatically.md
      - doc/faqs/how-to-install-untrusted-packages-safely.md
      - doc/faqs/how-to-use-composer-behind-a-proxy.md
      - doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md
      - doc/faqs/which-version-numbering-system-does-composer-itself-use.md
      - doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md
      - doc/faqs/why-are-version-constraints-combining-comparisons-and-wildcards-a-bad-idea.md
      - doc/faqs/why-cant-composer-load-repositories-recursively.md
